// Code generated by git.redmadrobot.com/backend-go/meroving. DO NOT EDIT.
package otp

import (
	"time"
	"your-company.com/project/pkg/redis"

	"your-company.com/project/pkg/grpcx"

	"your-company.com/project/pkg/logs"
)

type Application struct {
	Debug       bool
	Environment string

	MaxAttempts   int // Допустимое количество попыток ОТП (попыток) в рамках жизни одного запроса ОТП
	MaxCodeChecks int // Допустимое количество проверок совпадения кода для одной попытки

	NewAttemptDelay time.Duration // Время до запроса нового кода
	OtpRequestTTL   time.Duration // Время жизни запроса ОТП для расчета лимитов попыток
	CodeTTL         time.Duration // Время жизни кода ОТП (попытки)
}

func ApplicationDefault() *Application {
	return &Application{
		Debug:       true,
		Environment: "dev",

		MaxAttempts:   2,
		MaxCodeChecks: 3,

		NewAttemptDelay: 30 * time.Second,
		CodeTTL:         30 * time.Second,
		OtpRequestTTL:   3 * 60 * time.Second,
	}
}


type (
	Config struct {
		App    *Application
		GRPC   *grpcx.Config
		Logger *logs.Config
		Redis  *redis.Config
	}
)

func Load() *Config {
	return &Config{
		App:    ApplicationDefault(),
		GRPC:   grpcx.CfgDefault("50051"),
		Logger: logs.CfgDefault(),
		Redis:  redis.CfgDefault(),
	}
}
