// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: specs/proto/users/users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckReq) Reset() {
	*x = HealthCheckReq{}
	mi := &file_specs_proto_users_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckReq) ProtoMessage() {}

func (x *HealthCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_users_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckReq.ProtoReflect.Descriptor instead.
func (*HealthCheckReq) Descriptor() ([]byte, []int) {
	return file_specs_proto_users_users_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResp) Reset() {
	*x = HealthCheckResp{}
	mi := &file_specs_proto_users_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResp) ProtoMessage() {}

func (x *HealthCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_users_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResp.ProtoReflect.Descriptor instead.
func (*HealthCheckResp) Descriptor() ([]byte, []int) {
	return file_specs_proto_users_users_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DeviceInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstallationID string                 `protobuf:"bytes,1,opt,name=installationID,proto3" json:"installationID,omitempty"`
	AppVersion     string                 `protobuf:"bytes,2,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	DeviceModel    string                 `protobuf:"bytes,3,opt,name=deviceModel,proto3" json:"deviceModel,omitempty"`
	SystemType     string                 `protobuf:"bytes,4,opt,name=systemType,proto3" json:"systemType,omitempty"`
	SystemVersion  string                 `protobuf:"bytes,5,opt,name=systemVersion,proto3" json:"systemVersion,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_specs_proto_users_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_users_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_specs_proto_users_users_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceInfo) GetInstallationID() string {
	if x != nil {
		return x.InstallationID
	}
	return ""
}

func (x *DeviceInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *DeviceInfo) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *DeviceInfo) GetSystemType() string {
	if x != nil {
		return x.SystemType
	}
	return ""
}

func (x *DeviceInfo) GetSystemVersion() string {
	if x != nil {
		return x.SystemVersion
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,2,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_specs_proto_users_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_users_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_specs_proto_users_users_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginReq) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptID     string                 `protobuf:"bytes,1,opt,name=attemptID,proto3" json:"attemptID,omitempty"`
	RetryTime     int32                  `protobuf:"varint,2,opt,name=retryTime,proto3" json:"retryTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_specs_proto_users_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_users_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_specs_proto_users_users_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResp) GetAttemptID() string {
	if x != nil {
		return x.AttemptID
	}
	return ""
}

func (x *LoginResp) GetRetryTime() int32 {
	if x != nil {
		return x.RetryTime
	}
	return 0
}

type ConfirmLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptID     string                 `protobuf:"bytes,1,opt,name=attemptID,proto3" json:"attemptID,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmLoginReq) Reset() {
	*x = ConfirmLoginReq{}
	mi := &file_specs_proto_users_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmLoginReq) ProtoMessage() {}

func (x *ConfirmLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_users_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmLoginReq.ProtoReflect.Descriptor instead.
func (*ConfirmLoginReq) Descriptor() ([]byte, []int) {
	return file_specs_proto_users_users_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmLoginReq) GetAttemptID() string {
	if x != nil {
		return x.AttemptID
	}
	return ""
}

func (x *ConfirmLoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Access        string                 `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	Refresh       string                 `protobuf:"bytes,2,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_specs_proto_users_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_users_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_specs_proto_users_users_proto_rawDescGZIP(), []int{6}
}

func (x *Token) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *Token) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

type ConfirmLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NextStep      string                 `protobuf:"bytes,2,opt,name=nextStep,proto3" json:"nextStep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmLoginResp) Reset() {
	*x = ConfirmLoginResp{}
	mi := &file_specs_proto_users_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmLoginResp) ProtoMessage() {}

func (x *ConfirmLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_users_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmLoginResp.ProtoReflect.Descriptor instead.
func (*ConfirmLoginResp) Descriptor() ([]byte, []int) {
	return file_specs_proto_users_users_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmLoginResp) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ConfirmLoginResp) GetNextStep() string {
	if x != nil {
		return x.NextStep
	}
	return ""
}

var File_specs_proto_users_users_proto protoreflect.FileDescriptor

const file_specs_proto_users_users_proto_rawDesc = "" +
	"\n" +
	"\x1dspecs/proto/users/users.proto\x12\x05users\"\x10\n" +
	"\x0eHealthCheckReq\")\n" +
	"\x0fHealthCheckResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"\xbc\x01\n" +
	"\n" +
	"DeviceInfo\x12&\n" +
	"\x0einstallationID\x18\x01 \x01(\tR\x0einstallationID\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x02 \x01(\tR\n" +
	"appVersion\x12 \n" +
	"\vdeviceModel\x18\x03 \x01(\tR\vdeviceModel\x12\x1e\n" +
	"\n" +
	"systemType\x18\x04 \x01(\tR\n" +
	"systemType\x12$\n" +
	"\rsystemVersion\x18\x05 \x01(\tR\rsystemVersion\"S\n" +
	"\bLoginReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x121\n" +
	"\n" +
	"deviceInfo\x18\x02 \x01(\v2\x11.users.DeviceInfoR\n" +
	"deviceInfo\"G\n" +
	"\tLoginResp\x12\x1c\n" +
	"\tattemptID\x18\x01 \x01(\tR\tattemptID\x12\x1c\n" +
	"\tretryTime\x18\x02 \x01(\x05R\tretryTime\"C\n" +
	"\x0fConfirmLoginReq\x12\x1c\n" +
	"\tattemptID\x18\x01 \x01(\tR\tattemptID\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"9\n" +
	"\x05Token\x12\x16\n" +
	"\x06access\x18\x01 \x01(\tR\x06access\x12\x18\n" +
	"\arefresh\x18\x02 \x01(\tR\arefresh\"R\n" +
	"\x10ConfirmLoginResp\x12\"\n" +
	"\x05token\x18\x01 \x01(\v2\f.users.TokenR\x05token\x12\x1a\n" +
	"\bnextStep\x18\x02 \x01(\tR\bnextStep2\xb2\x01\n" +
	"\x05Users\x12<\n" +
	"\vHealthCheck\x12\x15.users.HealthCheckReq\x1a\x16.users.HealthCheckResp\x12*\n" +
	"\x05Login\x12\x0f.users.LoginReq\x1a\x10.users.LoginResp\x12?\n" +
	"\fConfirmLogin\x12\x16.users.ConfirmLoginReq\x1a\x17.users.ConfirmLoginRespB\x13Z\x11specs/proto/usersb\x06proto3"

var (
	file_specs_proto_users_users_proto_rawDescOnce sync.Once
	file_specs_proto_users_users_proto_rawDescData []byte
)

func file_specs_proto_users_users_proto_rawDescGZIP() []byte {
	file_specs_proto_users_users_proto_rawDescOnce.Do(func() {
		file_specs_proto_users_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_specs_proto_users_users_proto_rawDesc), len(file_specs_proto_users_users_proto_rawDesc)))
	})
	return file_specs_proto_users_users_proto_rawDescData
}

var file_specs_proto_users_users_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_specs_proto_users_users_proto_goTypes = []any{
	(*HealthCheckReq)(nil),   // 0: users.HealthCheckReq
	(*HealthCheckResp)(nil),  // 1: users.HealthCheckResp
	(*DeviceInfo)(nil),       // 2: users.DeviceInfo
	(*LoginReq)(nil),         // 3: users.LoginReq
	(*LoginResp)(nil),        // 4: users.LoginResp
	(*ConfirmLoginReq)(nil),  // 5: users.ConfirmLoginReq
	(*Token)(nil),            // 6: users.Token
	(*ConfirmLoginResp)(nil), // 7: users.ConfirmLoginResp
}
var file_specs_proto_users_users_proto_depIdxs = []int32{
	2, // 0: users.LoginReq.deviceInfo:type_name -> users.DeviceInfo
	6, // 1: users.ConfirmLoginResp.token:type_name -> users.Token
	0, // 2: users.Users.HealthCheck:input_type -> users.HealthCheckReq
	3, // 3: users.Users.Login:input_type -> users.LoginReq
	5, // 4: users.Users.ConfirmLogin:input_type -> users.ConfirmLoginReq
	1, // 5: users.Users.HealthCheck:output_type -> users.HealthCheckResp
	4, // 6: users.Users.Login:output_type -> users.LoginResp
	7, // 7: users.Users.ConfirmLogin:output_type -> users.ConfirmLoginResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_specs_proto_users_users_proto_init() }
func file_specs_proto_users_users_proto_init() {
	if File_specs_proto_users_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_specs_proto_users_users_proto_rawDesc), len(file_specs_proto_users_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_specs_proto_users_users_proto_goTypes,
		DependencyIndexes: file_specs_proto_users_users_proto_depIdxs,
		MessageInfos:      file_specs_proto_users_users_proto_msgTypes,
	}.Build()
	File_specs_proto_users_users_proto = out.File
	file_specs_proto_users_users_proto_goTypes = nil
	file_specs_proto_users_users_proto_depIdxs = nil
}
