// Code generated by git.redmadrobot.com/backend-go/meroving. DO NOT EDIT.
package users

import (
	"time"
	"your-company.com/project/pkg/redis"

	"your-company.com/project/pkg/grpcx"

	"your-company.com/project/pkg/logs"
)

type (
	Config struct {
		App    *Application
		GRPC   *grpcx.Config
		Logger *logs.Config
		Redis  *redis.Config
	}
)

func LoadDefault() *Config {
	return &Config{
		App:    ApplicationDefault(),
		GRPC:   grpcx.CfgDefault("50052"),
		Logger: logs.CfgDefault(),
		Redis:  redis.CfgDefault(),
	}
}

type Application struct {
	Debug                  bool
	Environment            string
	RefreshRetriesMax      int
	RefreshRetiresInterval time.Duration
}

func ApplicationDefault() *Application {
	return &Application{
		Debug:                  true,
		Environment:            "dev",
		RefreshRetriesMax:      3,
		RefreshRetiresInterval: 60 * time.Second,
	}
}
